spring.application.name=demo
server.port=8081

# --- CẤU HÌNH THÔNG MINH (TỰ ĐỘNG CHUYỂN ĐỔI RENDER/LOCAL) ---
# Dùng DB schoolmanagerxyz của dự án 8081 làm mặc định khi chạy trên máy
spring.datasource.url=${DB_URL:jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;databaseName=schoolmanagerxyz}

# Tài khoản sa và pass 123123 của dự án 8081
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:123123}

spring.datasource.driver-class-name=${DB_DRIVER_CLASS:com.microsoft.sqlserver.jdbc.SQLServerDriver}

# --- CẤU HÌNH KHÁC ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.forward-headers-strategy=framework
spring.thymeleaf.cache=false